FROM eclipse-mosquitto:latest

#COPY ./docker/mosquitto/config/pwfile /mosquitto/config/pwfile
#RUN chmod 0700 /mosquitto/config/pwfile

CMD ["/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]
